name: Check Python code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade poetry
          poetry install --with development

      - name: Run Python code checks
        run: |
          make check-python-code